/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Acl */

#ifndef _Included_Acl
#define _Included_Acl
#ifdef __cplusplus
extern "C" {
#endif
#undef Acl_BUFFER_SIZE
#define Acl_BUFFER_SIZE 1024L
#undef Acl_UINT_MAX
#define Acl_UINT_MAX 65535L
#undef Acl_NUM_AUTHS
#define Acl_NUM_AUTHS 6L
/*
 * Class:     Acl
 * Method:    getxattr
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_Acl_getxattr
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
